require 'victor'
require 'minichart/id_generator'
require 'minichart/base'
require 'minichart/charts/chart'
require 'minichart/charts/line_chart'
require 'minichart/charts/bar_chart'
require 'minichart/charts/area_chart'
require 'minichart/meters/meter'
require 'minichart/meters/vertical_bar_meter'
require 'minichart/meters/horizontal_bar_meter'
require 'minichart/leds/leds'
require 'minichart/leds/horizontal_status_leds'
require 'minichart/leds/vertical_status_leds'

require 'byebug' if ENV['BYEBUG']